---
title: "Microdata Library Catalog"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load Packages
library(tidyverse)
library(skimr)
library(kableExtra)
library(readxl)
library(Hmisc)
library(haven)
library(gt)
library(httr)
library(jsonlite)
library(tidytext)
library(rsdmx)
library(here)

# Directory for SPI csv files  to be created

output_dir <- paste(here(),"/Resources/Microdata_Catalog/03_outputs/", sep="")
```

## Introduction

This file will pull metadata from the microdata library programmatically using the Microdata library API.

Below we pull data from both the public, non-public (World Bank use only) microdata, and IHSN libraries using a restful API.  We will produce a dataframe for each of these sources containing the basic metadata for each survey included.

```{r data_pulls}

#public studies from World Bank microdata library
public_base_url <- "http://microdata.worldbank.org/index.php/api/catalog" #define url
study_request_public<-fromJSON(paste(public_base_url,"/search","?ps=10000", sep="")) # pull from url
study_df_public <- study_request_public$result$rows #convert to dataframe
write_excel_csv(study_df_public, path = paste(output_dir, "microdata_library_public_studies.csv")) #write to csv
gt(as_tibble(head(study_df_public[,1:5]))) #display top 5 rows of dataframe


#internal use studies from World Bank microdata library
wb_base_url <- "http://microdatalib.worldbank.org/index.php/api/catalog" #define url
study_request_wb<-fromJSON(paste(wb_base_url,"/search","?ps=10000", sep="")) # pull from url
study_df_internal <- study_request_wb$result$rows
write_excel_csv(study_df_internal, path = paste(output_dir, "microdata_library_internal_studies.csv")) #write to csv
gt(as_tibble(head(study_df_internal[,1:5])))

# pull all studies from IHSN
ihsn_base_url <- "https://catalog.ihsn.org/index.php/api/catalog" #define url
study_request_ihsn<-fromJSON(paste(ihsn_base_url,"/search","?ps=10000", sep="")) # pull from url
study_df_ihsn <- study_request_ihsn$result$rows #convert to dataframe
write_excel_csv(study_df_ihsn, path = paste(output_dir, "ihsn_library_public_studies.csv")) #write to csv
gt(as_tibble(head(study_df_ihsn[,1:5]))) #display top 5 rows of dataframe




```

